version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: vitaladmin
      POSTGRES_PASSWORD: SecurePass456
      POSTGRES_DB: vitalview_db
    ports:
      - "5432:5432"
    volumes:
      - vitalview1_pgdata:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@vitalview.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: always

  backup:
    build: ./backup
    volumes:
      - ./backups:/backups
    depends_on:
      - db
    restart: always

volumes:
  vitalview1_pgdata:

