"""Add hashed_password to User

Revision ID: 0ca96667fdfd
Revises: 2d2c7a6cc658
Create Date: 2025-06-14 20:37:54.103053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ca96667fdfd'
down_revision: Union[str, None] = '2d2c7a6cc658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inlog_gegevens', sa.Column('hashed_password', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inlog_gegevens', 'hashed_password')
    # ### end Alembic commands ###
