"""Add missing tables

Revision ID: 2b629c503aa7
Revises: 0ca96667fdfd
Create Date: 2025-06-15 16:15:44.909230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b629c503aa7'
down_revision: Union[str, None] = '0ca96667fdfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_bericht',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naam', sa.String(length=100), nullable=False),
    sa.Column('emailadres', sa.String(length=120), nullable=False),
    sa.Column('onderwerp', sa.String(length=100), nullable=False),
    sa.Column('telefoonnummer', sa.String(length=20), nullable=True),
    sa.Column('bericht', sa.Text(), nullable=False),
    sa.Column('verzonden_op', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_message',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('contact_message_pkey'))
    )
    op.drop_table('contact_bericht')
    # ### end Alembic commands ###
